### PR TITLE
Jdobkins agrandje

### PR DESCRIPTION
**Pull request by jsd1710**
Merging issue closures.

### CODE REVIEW

**Comment by msmtms** [comment]
The @author for javadoc in Main.java for the class header should be removed (or moved) but should be created as another issue. Otherwise, the merge should be fine.

**Comment by jsd1710** [comment]
Technically, we did not perform a modification on the existing "@author" line, therefore you need to open a new Issue and pursue the issue! Word, son.

**Comment by davisk** [comment]
The standard doesn't change no matter the issue.

**Comment by jsd1710** [comment]
The issue is that this is a separate issue, create yo own branch!

**Comment by davisk** [comment]
ok

**Pull request closed without merging**
